
[mongodb]
mongodb-dev.swamy.sbs

[catalogue]
catalogue-dev.swamy.sbs
[redis]
redis-dev.swamy.sbs
[user]
user-dev.swamy.sbs
[cart]
cart-dev.swamy.sbs
[mysql]
mysql-dev.swamy.sbs
[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.swamy.sbs
CATALOGUE_HOST=catalogue-dev.swamy.sbs
REDIS_HOST=redis-dev.swamy.sbs
USER_HOST=user-dev.swamy.sbs
CART_HOST=cart-dev.swamy.sbs
MYSQL_HOST=mysql-dev.swamy.sbs



