- name: demo on error handling
  hosts: local
  connection: local
  become: true
  tasks:
  - name: check user is exist or not
    ansible.builtin.command: id swamy
    register: user_ouput
    ignore_errors: true
  - name: print user details 
    ansible.builtin.debug:
      msg: "{{ user_ouput }}"  
  - name: create user swamy
    ansible.builtin.command: useradd swamy
    when: user_ouput.rc != 0
